title: INFORMASI PALING BARU DARI DALAM DAN LUAR NEGRI
description: Informasi yang kamu dapatkan merupakan informasi yang paling akurat dan sangat aktual, update setiap hari!
remote_theme: mmistakes/minimal-mistakes@4.27.1

plugins:
  - jekyll-include-cache
  - jekyll-feed

author:
  name: palingbaru

atom_feed:
  path: feed.xml
<script defer data-domain="github.com/tejera-a11y/palingbaru" src="https://plausible.io/js/script.file-downloads.hash.outbound-links.pageview-props.revenue.tagged-events.js"></script>
<script>window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }</script>
