title: INFORMASI PALING BARU DARI DALAM DAN LUAR NEGRI
description: Informasi yang kamu dapatkan merupakan informasi yang paling akurat dan sangat aktual, update setiap hari!
remote_theme: mmistakes/minimal-mistakes@4.27.1

plugins:
  - jekyll-include-cache
  - jekyll-feed

author:
  name: palingbaru

atom_feed:
  path: feed.xml
